### ISSUE TITLE
How to use with an array of files

### ISSUE THREAD

**Issue by PapePathe** [brandonsavage/Upload#32]
Hello to All contributors i want to use the library to upload multiple files in the same request...

Any HOW TO would be a great help.

Actually using it on a client project & it works well....

**Comment by mrbarletta** [comment]
try {
            //Trying to save the File
            $file->upload();
            echo json_encode($results);
        } catch (\Exception $e) {
            $results[]=$file->getErrors();
            error_log(__FILE__." ". __LINE__." ". print_r($e, 1));
            echo json_encode($results);
        }
