### ISSUE TITLE
empty file submission

### ISSUE THREAD

**Issue by allocaz** [brandonsavage/Upload#47]
Hello,

First, thanks for your work !!
I've noted that sending empty file raise an error after creating the file and setting a new name if the submitted file is not setted

$file  = new File($name, $storage);
$file->setName( $name );   [raise error if key ok but error code 4]

You raise an exception if a not existing key is submitted but you don't check the error 4 (empty path) when creating a new name.

Perhaps i'm not using correctly the API. Let me know.
I do my own check in the meantime.

With regards,
Rodney

**Comment by jakjr** [comment]
Hi,

in dev-master version, an exception is raised if we try submit an empty input file.

The array errors on line 133 of file File.php should ignore errors  #4.

Thanks.
