### ISSUE TITLE
File upload Empty

### ISSUE THREAD

**Issue by carlos-andres** [brandonsavage/Upload#50]
Good Day, i try to use this library on a simple slim framework project, 

then using all the basic code and try to upload file it works and no error message appears, but when i check the upload folder it´s empty, also i attach the dump vars.

there is any that i miss?... many thanks

![screen shot 2014-09-27 at 9 39 25 am](https://cloud.githubusercontent.com/assets/5489747/4431031/4af0894c-4654-11e4-9440-e7652442fe08.png)

**Comment by brandonsavage** [comment]
Has this issue been resolved?

**Comment by carlos-andres** [comment]
aparently there is no error.. but thanks
