### ISSUE TITLE
Class finfo not found

### ISSUE THREAD

**Issue by donwildman** [brandonsavage/Upload#73]
Hi,
I'm using Laravel 4.2 with your library installed by composer.
Suddenly yesterday I started to get this error:
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'finfo' not found' in /home/tmyndrzy/public_html/vendor/codeguy/upload/src/Upload/File.php:203

There have been no environment changes that I am aware of, I'm using PHP 5.4.

**Comment by brandonsavage** [comment]
Class finfo is a built-in for PHP. This is a problem with your PHP installation.

**Comment by donwildman** [comment]
Hi Brandon,

My apologies, I tracked that down after I posted.

Regards,

Don

FGX Studios
Mallguide <http://www.mallguide.co.za> | CMS Ignition 
<www.cmsignition.co.za> | Disclaimer 
<http://www.fgx.co.za/disclaimer.htm> | FB 
<https://www.facebook.com/fgxstudios> | Twitter 
<https://twitter.com/fgxstudios> | LinkedIn 
<http://za.linkedin.com/in/fgxstudios>

**Comment by dkikan** [comment]
Would really appreciate if you can share the fix.
