### ISSUE TITLE
getNameWithExtension() returning a number

### ISSUE THREAD

**Issue by mayurpande** [brandonsavage/Upload#90]
Uploading the image is working fine, however it is uploading an image that should be called 

> buttons.png

as 

>  57a479252173e.png

Is there a way I can use `getNameWithExtension` to upload the correct name?

**Comment by williamespindola** [comment]
It seems like `uniqid()`. if you see at the README of project exists some optionally definition of file name using the `uniqid` function, maybe you accidentally copy that and now your code is change file name.

**Comment by mayurpande** [comment]
Thanks, this was the problem
