### ISSUE TITLE
multiple file uploads

### ISSUE THREAD

**Issue by Oirere-Jr** [brandonsavage/Upload#96]
How do you upload multiple files eg photos

**Comment by mugenyi** [comment]
i had the same problem but after a closer look at the code i found out that the current package on github supports multiple file upload but the last release "1.3.2" does not and thats what composer will install by default. 
you can install the master branch with this command.

    composer require   codeguy/upload "dev-master"
it will do the trick.

**Comment by farizluqman** [comment]
+1 mugenyi
