### ISSUE TITLE
How to upload?

### ISSUE THREAD

**Issue by night-cypher** [brandonsavage/Upload#97]
Hi... i had try the example but its dont work...

$file = new \Upload\File('foo', $storage);
is this variable same as $_FILES?

**Comment by yuriygr** [comment]
`foo` is name yout upload input

**Comment by night-cypher** [comment]
i tested.... but get slim application error.

**Comment by night-cypher** [comment]
I had error from the 1st line
$storage = new \Upload\Storage\FileSystem('/upload');
